version: '3.8'
services:

  database:
    platform: linux/x86_64
    container_name: database
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5
  app:
      build:
        context: .
        dockerfile: Dockerfile

      command: 'sh /app/migrate_and_serve.sh'
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        database:
          condition: service_healthy


